# -*- coding: utf-8 -*-
"""Analysis with Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rWypaTxiHCeJV5TDqZ_y_rg6MDGGJ5iH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Check and get current working directory
import os
print(os.getcwd())

# Connecting to google colab
from google.colab import drive
drive.mount('/content/drive')

# Extract dataset from google drive
dataset = ('/content/drive/MyDrive/MyDataSet/fmcg_regional_sales_data.xlsx')
df = pd.read_excel(dataset)

df.head()

df.shape

df.info()

df.isnull().sum()

Ret_Rate = df['Units Returned'] / df['Sales Volume']
df['Return Rate'] = Ret_Rate.round(2) * 100

df.head()

df.isnull().sum()

df.shape

df.isnull().sum()

df['Competitor Promotions']

High_occur = df['Competitor Promotions'].mode()

df['Competitor Promotions'].fillna(High_occur[0], inplace=True)

df.isnull().sum()

df['Customer Complaints']

print(df['Customer Complaints'].value_counts())

df['Customer Complaints'].fillna('No Complaint', inplace=True)

df.isnull().sum()

df.head()

df.groupby(df['Distributor Availability']).count()

df[['Sales Volume','Units Returned']].agg(['min', 'max', 'mean']).plot(kind='bar')

df['Customer Complaints'].value_counts()

df['Customer Complaints'].value_counts().plot(kind='bar')
plt.xlabel('Customer Complaints')
plt.ylabel('Count')
plt.title('Distribution of Customer Complaints')
plt.show()

df.head()

df['Competitor Promotions'].value_counts().plot(kind = 'bar')
plt.xlabel('Competitor Promotions')
plt.ylabel('Count')
plt.title('Distribution of Competitor Promotions')

df.head()

df.groupby(df['Product Name'])

df['Product Name'].groupby(df['Product Name']).count()

# The lambda function there is to format the sales volume well formatted with comma
df['Sales Volume'].groupby(df['Product Name']).sum().sort_values(ascending=False).apply(lambda x: f'{x:,}')

df['Units Returned'].groupby(df['Product Name']).sum().sort_values(ascending=False).apply(lambda x: f'{x:,}')

df['Sales Volume'].groupby(df['Store ID']).sum().sort_values(ascending=False).apply(lambda x: f'{x:,}').head(10)

